# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: kicker_stats_development
  host: localhost
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql
  database: kicker_stats_test
  host: localhost
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql
  database: kicker_stats_production
  host: localhost
  username: root
  password:
  encoding: utf8
